(function(){
'use strict';
var $=function(id){return document.getElementById(id)};
var samples={
microsoft:{provider:'outlook',subject:'URGENT: Your Microsoft 365 account will be suspended',raw:'From: Microsoft Account Team <security@micros0ft-verify.example.test>\nReply-To: helpdesk@account-recovery.example.test\nReturn-Path: <bounce@mailer.example.test>\nAuthentication-Results: mx.example.test; spf=fail smtp.mailfrom=mailer.example.test; dkim=none; dmarc=fail header.from=micros0ft-verify.example.test\n\nYour Microsoft 365 mailbox will be disabled in 30 minutes. Sign in now to keep access. Confirm your password and one-time code at https://microsoft-login-check.example.test/session. Do not contact IT because this automated verification is confidential.',note:'Fictional Microsoft impersonation sample. All example.test domains are reserved for documentation and are not real login destinations.'},
google:{provider:'gmail',subject:'Google Drive storage warning — action required',raw:'From: Google Storage <drive-alert@google-storage-review.example.test>\nReply-To: storage-help@unrelated-mail.example.test\nReturn-Path: <bulk@unrelated-mail.example.test>\nAuthentication-Results: mx.example.test; spf=fail; dkim=fail; dmarc=fail\n\nYour Google Drive files will be permanently deleted today. Open https://google-drive-recover.example.test/restore and enter your Google password and verification code. Pay a small reactivation fee if requested.',note:'Fictional Google-themed phishing sample. Sender and destination domains are deliberately untrusted examples.'},
safe:{provider:'gmail',subject:'Community library: book due next Tuesday',raw:'From: Community Library <reminders@library.example.test>\nReply-To: reminders@library.example.test\nReturn-Path: <reminders@library.example.test>\nAuthentication-Results: mx.example.test; spf=pass; dkim=pass; dmarc=pass\n\nA friendly reminder that your borrowed book is due next Tuesday. You can check loan details at the library desk. No payment or account action is needed today.',note:'Synthetic low-risk control sample. The displayed authentication results are sample header text, not a live verification.'},
invoice:{provider:'outlook',subject:'Updated invoice — payment details changed',raw:'From: Accounts Payable <billing@vendor-payment-change.example.test>\nReply-To: finance-urgent@free-mail.example.test\nReturn-Path: <bulk@mailer.example.test>\nAuthentication-Results: mx.example.test; spf=pass smtp.mailfrom=mailer.example.test; dkim=pass header.d=mailer.example.test; dmarc=fail header.from=vendor-payment-change.example.test\n\nWe have changed our bank account. Please pay the attached invoice today to avoid service interruption. Do not call the usual contact because the finance team is in a meeting.',note:'Fictional business-email-compromise (BEC) sample. Payment-detail changes should be verified using a previously known contact method.'}
};
var brandDomains={Microsoft:['microsoft.com','microsoftonline.com','office.com','live.com','outlook.com'],Google:['google.com','googlemail.com','gmail.com'],Apple:['apple.com','icloud.com'],Amazon:['amazon.com','amazon.in'],PayPal:['paypal.com'],Meta:['facebook.com','meta.com','instagram.com'],Netflix:['netflix.com']};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function getDomain(address){var m=String(address||'').match(/@([a-z0-9.-]+\.[a-z]{2,})/i);return m?m[1].toLowerCase().replace(/[)>.,;]+$/,''):''}
function parseHeaders(raw){var parts=String(raw||'').replace(/\r\n/g,'\n').split('\n\n'),head=parts.shift()||'',body=parts.join('\n\n'),lines=head.split('\n'),unfold=[];lines.forEach(function(line){if(/^\s/.test(line)&&unfold.length)unfold[unfold.length-1]+=' '+line.trim();else unfold.push(line)});var h={};unfold.forEach(function(line){var p=line.indexOf(':');if(p>0){var k=line.slice(0,p).trim().toLowerCase(),v=line.slice(p+1).trim();h[k]=(h[k]?h[k]+'\n':'')+v}});return {headers:h,body:body}}
function getClaimedBrand(text,from){var hay=(String(text||'')+' '+String(from||'')).toLowerCase(),map=[['Microsoft',/microsoft|office 365|microsoft 365|outlook/],['Google',/google|gmail|google drive/],['Apple',/\bapple\b|icloud/],['Amazon',/amazon/],['PayPal',/paypal/],['Meta',/\bmeta\b|facebook|instagram/],['Netflix',/netflix/],['Bank / financial institution',/\bbank\b|kyc|upi|account security|credit card/],['Courier / delivery',/delivery|parcel|courier|shipment/]];for(var i=0;i<map.length;i++)if(map[i][1].test(hay))return map[i][0];return 'Unknown / unclassified'}
function analyze(raw,selectedProvider){
 var p=parseHeaders(raw),h=p.headers,body=p.body,full=String(raw||''),from=h.from||'',reply=h['reply-to']||'',ret=h['return-path']||'',subject=h.subject||$('mailSubject').value||'',auth=(h['authentication-results']||'')+' '+(h['received-spf']||''),senderDomain=getDomain(from),replyDomain=getDomain(reply),returnDomain=getDomain(ret),brand=getClaimedBrand(subject+' '+body,from),hits=[],score=0;
 function hit(test,title,detail,weight,kind){if(test){hits.push({title:title,detail:detail,kind:kind||'risk'});score+=weight}}
 var urls=(full.match(/https?:\/\/[^\s<>"')]+/ig)||[]),urlDomains=[];urls.forEach(function(u){try{urlDomains.push(new URL(u).hostname.toLowerCase())}catch(e){}});
 var authLower=auth.toLowerCase(),spf=authLower.match(/\bspf\s*=\s*(pass|fail|softfail|neutral|none|temperror|permerror)\b/),dkim=authLower.match(/\bdkim\s*=\s*(pass|fail|none|neutral|temperror|permerror)\b/),dmarc=authLower.match(/\bdmarc\s*=\s*(pass|fail|none|bestguesspass)\b/),authFound=!!(spf||dkim||dmarc);
 hit(/urgent|immediately|within \d+|will be (disabled|suspended|blocked)|permanently deleted|final warning|act now|today/i.test(subject+' '+body),'Urgency or loss threat','The message uses a deadline or threatens account/data loss.',16);
 hit(/password|one.time code|verification code|security code|otp|pin|cvv|sign in now|enter your credentials/i.test(body),'Credential or verification-code request','The text asks for secrets or directs the recipient to a sign-in/verification flow.',25);
 hit(/pay(ment)? (a |the )?(fee|invoice|reactivation)|bank account|bank details|wire transfer|payment details changed|new bank account|upi|refund/i.test(subject+' '+body),'Financial action or payment-change request','Payment language or changed payment details can be abused; verify independently.',19);
 hit(/do not (contact|call|tell)|keep .* confidential|do not reply|secret|no time to/i.test(body),'Secrecy or verification avoidance','The sender discourages independent verification or normal contact.',13);
 hit(urls.length>0,'Link(s) present','Links were extracted from the supplied text. Presence alone does not establish maliciousness or reputation.',7,'info');
 hit(/\.apk\b|\.exe\b|\.scr\b|\.js\b|\.iso\b|\.zip\b|enable macros|macro-enabled|open the attachment/i.test(full),'Potentially risky attachment language','The email mentions an executable or attachment action. This tool does not inspect attachment bytes.',20);
 hit(/spf\s*=\s*(fail|softfail|permerror)|dkim\s*=\s*(fail|none|permerror)|dmarc\s*=\s*(fail|none)/i.test(auth),'Authentication failure reported in pasted headers','The supplied Authentication-Results text reports one or more failures. Headers are user-supplied and have not been cryptographically verified here.',23);
 hit(/spf\s*=\s*pass/i.test(auth),'SPF pass reported','A pasted header reports SPF pass; this alone does not prove the visible From identity is legitimate.',0,'info');
 hit(/dkim\s*=\s*pass/i.test(auth),'DKIM pass reported','A pasted header reports DKIM pass; alignment with the visible From domain still matters.',0,'info');
 hit(/dmarc\s*=\s*pass/i.test(auth),'DMARC pass reported','A pasted header reports DMARC pass. This is useful evidence, not proof that the message content is safe.',0,'info');
 hit(!authFound,'No authentication results supplied','Paste the original full headers to inspect reported SPF/DKIM/DMARC results. No live authentication check was performed.',5,'gap');
 hit(!!replyDomain&&!!senderDomain&&replyDomain!==senderDomain,'Reply-To differs from From domain','The reply destination uses a different domain. Some legitimate services do this, but unexpected differences deserve review.',18);
 hit(!!returnDomain&&!!senderDomain&&returnDomain!==senderDomain&&returnDomain!==senderDomain+'.'&&!returnDomain.endsWith('.'+senderDomain),'Return-Path differs from From domain','The bounce address uses another domain. Mailing platforms can legitimately differ; compare with authentication and context.',8);
 var allowed=brandDomains[brand]||[];
 if(senderDomain&&allowed.length){var aligned=allowed.some(function(d){return senderDomain===d||senderDomain.endsWith('.'+d)});hit(!aligned,'Claimed brand and sender domain do not align','The content appears to reference '+brand+', but the parsed sender domain is '+senderDomain+'. This is an impersonation indicator, not a definitive verdict.',24);var typo=allowed.some(function(d){var base=d.split('.')[0];return senderDomain.indexOf(base)>=0&&senderDomain!==d&&!senderDomain.endsWith('.'+d)});hit(typo,'Possible brand-lookalike domain','The sender domain contains a brand-like string without matching the known domain. Inspect spelling and registrable domain carefully.',12)}
 if(urlDomains.length&&senderDomain)hit(urlDomains.some(function(d){return d!==senderDomain&&!d.endsWith('.'+senderDomain)}),'Link host differs from sender domain','At least one link uses a different host from the sender domain. This can be legitimate but should be checked before clicking.',10);
 hit(/unsubscribe|newsletter|sale ends|limited offer/i.test(subject+' '+body)&&!/(password|otp|urgent|payment|bank details)/i.test(body),'Possible bulk / promotional mail','Promotional language appears without strong credential or payment pressure.',0,'info');
 score=Math.max(0,Math.min(100,score));
 var verdict=score>=65?'HIGH RISK INDICATORS':score>=38?'SUSPICIOUS — REVIEW':score>=18?'CAUTION — VERIFY':'LOWER SIGNAL — NOT VERIFIED';
 var category=/(password|otp|verification code|credentials|sign in now)/i.test(body)?'Credential phishing':/payment details changed|new bank account|wire transfer/i.test(subject+' '+body)?'Possible business email compromise':/\.apk\b|\.exe\b|\.scr\b|attachment/i.test(full)?'Attachment / malware risk':/payment|invoice|refund|fee|upi|bank details/i.test(subject+' '+body)?'Financial / payment scam indicators':urls.length?'Link-based email — inspect destination':'General email triage';
 var providerLabel={gmail:'Gmail',outlook:'Outlook / Microsoft 365',yahoo:'Yahoo Mail',other:'Other / custom mail'}[selectedProvider]||'Other / custom mail';
 return {score:score,verdict:verdict,category:category,brand:brand,provider:providerLabel,from:from||'Not parsed',senderDomain:senderDomain||'Not parsed',reply:reply||'Not supplied',replyDomain:replyDomain||'Not parsed',returnPath:ret||'Not supplied',returnDomain:returnDomain||'Not parsed',subject:subject||'No subject parsed',urls:urlDomains,authStatus:authFound?'Reported in pasted headers':'Not provided',auth:{spf:spf?spf[1].toUpperCase():'NOT PROVIDED',dkim:dkim?dkim[1].toUpperCase():'NOT PROVIDED',dmarc:dmarc?dmarc[1].toUpperCase():'NOT PROVIDED'},hits:hits,note:'Heuristic local screening. Pasted headers are not trusted proof; no DNS lookup, DKIM cryptographic verification, mailbox connection, attachment scanning, or live URL reputation check was performed.'}
}
function renderResult(r){
 var cls=r.score>=65?'risk-high':r.score>=38?'risk-mid':'risk-low';
 $('mailResult').classList.remove('empty-state');$('mailResult').innerHTML='<div class="mail-result-top"><div><div class="eyebrow">LOCAL TRIAGE OUTPUT</div><h3>'+esc(r.verdict)+'</h3><p>'+esc(r.category)+'</p></div><div class="mail-score '+cls+'"><strong>'+r.score+'</strong><small>indicator index / 100</small></div></div><div class="mail-summary-grid"><div><small>MAILBOX SELECTED</small><b>'+esc(r.provider)+'</b></div><div><small>CLAIMED BRAND</small><b>'+esc(r.brand)+'</b></div><div><small>PARSED SENDER DOMAIN</small><b>'+esc(r.senderDomain)+'</b></div><div><small>AUTH HEADER</small><b>'+esc(r.authStatus)+'</b></div></div><div class="mail-auth-grid">'+[['SPF',r.auth.spf],['DKIM',r.auth.dkim],['DMARC',r.auth.dmarc]].map(function(a){var c=a[1]==='PASS'?'auth-pass':a[1]==='FAIL'?'auth-fail':'auth-unknown';return '<div class="mail-auth-item '+c+'"><small>'+a[0]+'</small><b>'+a[1]+'</b></div>'}).join('')+'</div><div class="mail-result-section"><h4>Why it was classified this way</h4>'+r.hits.map(function(h){return '<div class="mail-finding '+esc(h.kind)+'"><span>'+(h.kind==='risk'?'!':h.kind==='gap'?'?':'i')+'</span><div><b>'+esc(h.title)+'</b><p>'+esc(h.detail)+'</p></div></div>'}).join('')+'</div><div class="mail-result-section"><h4>Identity and destination review</h4><dl class="mail-details"><dt>From</dt><dd>'+esc(r.from)+'</dd><dt>Reply-To</dt><dd>'+esc(r.reply)+'</dd><dt>Return-Path</dt><dd>'+esc(r.returnPath)+'</dd><dt>Extracted link hosts</dt><dd>'+esc(r.urls.length?r.urls.join(', '):'No links extracted')+'</dd></dl></div><div class="mail-safety-note"><b>Important boundary</b><p>'+esc(r.note)+'</p></div>'
}
function loadSample(key){var s=samples[key];if(!s)return;$('mailProvider').value=s.provider;$('mailSubject').value=s.subject;$('mailRaw').value=s.raw;$('mailSampleNote').textContent=s.note;$('mailResult').className='empty-state';$('mailResult').textContent='Sample loaded. Select “Analyze email” to run the local checks.'}
function init(){
 if(!$('mailAnalyze'))return;
 $('mailAnalyze').addEventListener('click',function(){var raw=$('mailRaw').value.trim();if(!raw){$('mailSampleNote').textContent='Paste email text or full headers first, or load a fictional example.';return}var started=performance.now(),r=analyze(raw,$('mailProvider').value);renderResult(r);$('mailRunMeta').textContent='Completed in '+Math.round(performance.now()-started)+' ms · browser-local rules · no network request made.'});
 document.querySelectorAll('[data-mail-sample]').forEach(function(b){b.addEventListener('click',function(){loadSample(b.dataset.mailSample)})});
 $('mailClear').addEventListener('click',function(){$('mailRaw').value='';$('mailSubject').value='';$('mailResult').className='empty-state';$('mailResult').textContent='Paste an email or load a fictional example to begin.';$('mailRunMeta').textContent='No analysis run yet.';$('mailSampleNote').textContent='Use fictional or redacted data. Do not paste passwords, OTPs, or private mail without permission.'});
 $('mailFile').addEventListener('change',function(){var f=this.files&&this.files[0];if(!f)return;if(f.size>1024*1024){$('mailSampleNote').textContent='Please choose an .eml file smaller than 1 MB.';this.value='';return}var reader=new FileReader();reader.onload=function(){$('mailRaw').value=String(reader.result||'');$('mailSampleNote').textContent='Loaded '+f.name+' locally in this browser. Nothing was uploaded.'};reader.onerror=function(){$('mailSampleNote').textContent='Could not read this file. Paste its text instead.'};reader.readAsText(f)});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();