(function(){
'use strict';
var $=function(id){return document.getElementById(id)};
var events=[
 {time:'09:41',title:'The bait arrives',channel:'SMS',kind:'Observed signal',summary:'A message claims to be from a bank and threatens account restriction.',body:'Your account will be restricted today. Verify your details at the linked page to keep access.',evidence:[['Authority impersonation','The message claims bank authority; the sender identity is not verified.'],['Urgency pressure','“Today” and threatened restriction encourage rushed action.'],['Link invitation','The text asks the recipient to open a page; no reputation lookup has occurred.']],inference:'Possible initial contact / trust pretext',gap:'The actual sender, destination ownership and message authenticity are unknown.'},
 {time:'09:43',title:'The link is inspected',channel:'WEB',kind:'Simulated action',summary:'The fictional user opens a lookalike verification page in the training sandbox.',body:'The training page asks the user to continue account verification. No external website is opened and no data is entered.',evidence:[['Action in simulation','The scenario records a fictional click; this is not device telemetry.'],['Credential collection risk','A verification page could solicit secrets, but the demo does not submit any.']],inference:'Potential credential-harvesting stage',gap:'No live URL reputation, page source or domain ownership has been checked.'},
 {time:'09:46',title:'A support call escalates pressure',channel:'CALL',kind:'Simulated action',summary:'A supposed support agent asks the user to share a verification code.',body:'The caller says the code is needed to stop account restriction and urges the user not to end the call.',evidence:[['One-time code request','Sharing an OTP or authentication code can let another party authorize an action.'],['Secrecy and urgency','The pressure reduces time for independent verification.']],inference:'Possible credential / account-takeover attempt',gap:'Caller identity and any real account activity remain unverified.'},
 {time:'09:47',title:'A payment action is proposed',channel:'PAYMENT',kind:'Simulated action',summary:'The fictional flow introduces an unexpected UPI approval request.',body:'The user is told to approve a request to receive a refund. In real UPI collect flows, approving may authorize an outgoing payment.',evidence:[['Unexpected payment request','The action may move money rather than receive it; inspect the exact app screen.'],['Earlier context','The request follows the simulated bank warning and code request in this story.']],inference:'Potential payment diversion / social-engineering stage',gap:'No real payment, recipient or transaction has been verified.'},
 {time:'09:48',title:'Potential loss point',channel:'OUTCOME',kind:'Hypothetical outcome',summary:'If the user approves the request, the scenario branches to a potential loss outcome.',body:'This is a counterfactual branch for training. No payment is made, no account is accessed, and no loss is observed.',evidence:[['Conditional outcome only','The simulated loss occurs only if the risky branch is chosen.'],['Prevention opportunity','A warning before sharing a code or approving payment may interrupt the flow.']],inference:'Potential impact—not a confirmed incident',gap:'The training result is not a prediction of what would happen in every real case.'}
];
var idx=0,started=false,choice=null;
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function renderTimeline(){
 $('reconTimeline').innerHTML=events.slice(0,started?idx+1:0).map(function(e,i){return '<button class="recon-event '+(i===idx?'active':'')+'" data-recon-event="'+i+'"><span class="recon-event-num">'+String(i+1).padStart(2,'0')+'</span><span><b>'+esc(e.title)+'</b><small>'+esc(e.channel)+' · '+esc(e.summary)+'</small></span><time>'+e.time+'</time></button>'}).join('')||'<div class="empty-state">Press Reconstruct attack to begin the fictional case.</div>';
 $('reconProgress').textContent=(started?idx+1:0)+' / '+events.length+' EVENTS';$('reconRange').value=started?idx:0;
}
function renderDetail(){
 if(!started){$('reconEventDetail').innerHTML='<div class="empty-state">Press Reconstruct attack to begin the fictional case.</div>';return}
 var e=events[idx];
 $('reconEventDetail').innerHTML='<div class="recon-detail-card"><div class="recon-detail-meta"><span class="recon-tag">'+esc(e.kind)+'</span><span class="recon-tag inferred">Inference: not proof</span></div><h4>'+esc(e.title)+'</h4><p>'+esc(e.body)+'</p><div class="recon-proof">'+e.evidence.map(function(x){return '<div class="recon-proof-item"><span>✓</span><div><b>'+esc(x[0])+'</b><small>'+esc(x[1])+'</small></div></div>'}).join('')+'</div><p style="margin-top:11px"><b>Evidence gap:</b> '+esc(e.gap)+'</p></div>';
 $('reconEvidence').innerHTML='<div class="recon-proof">'+e.evidence.map(function(x){return '<div class="recon-proof-item"><span>!</span><div><b>'+esc(x[0])+'</b><small>'+esc(x[1])+'</small></div></div>'}).join('')+'<div class="recon-proof-item"><span>?</span><div><b>What is not established</b><small>'+esc(e.gap)+'</small></div></div></div>';
 $('reconVerdictTitle').textContent=e.inference;$('reconVerdictText').textContent='This is a candidate stage inferred from the fictional scenario. Corroboration is required before treating it as a real finding.';
 $('reconBreakpoints').innerHTML=[
 ['First contact','Warn about urgency, unexpected account threats and links. Verify through the official bank app or a known contact.'],
 ['Before sharing a code','Never share an OTP or authentication code with an incoming caller. End the call and contact the institution independently.'],
 ['Before approving payment','Read the exact UPI screen. Do not approve an unexpected request to receive a refund.']
 ].map(function(b,i){return '<div class="breakpoint '+(i===0?'earliest':'')+'"><span>'+(i===0?'★':i+1)+'</span><div><b>'+(i===0?'EARLIEST PRACTICAL STOP · ':'')+esc(b[0])+'</b><small>'+esc(b[1])+'</small></div></div>'}).join('');
}
function start(){started=true;idx=0;choice=null;document.querySelectorAll('[data-choice]').forEach(function(b){b.classList.remove('selected')});$('challengeResult').className='challenge-result';$('challengeResult').innerHTML='<b>Choose an action to run the experiment.</b><p>No real website, message, account or payment is contacted.</p>';$('reconHeadline').textContent='Attack replay initiated';$('reconIntro').textContent='Move through the timeline, inspect the evidence, and distinguish observed events from candidate explanations.';renderTimeline();renderDetail()}
function choose(v){
 choice=v;document.querySelectorAll('[data-choice]').forEach(function(b){b.classList.toggle('selected',b.dataset.choice===v)});
 var box=$('challengeResult');
 if(v==='verify'){box.className='challenge-result success';box.innerHTML='<b>Safer branch selected: stop before exposure.</b><p>In this fictional replay, the chain is interrupted at the first contact. Verify through the official app or a known number. This is the preferred defensive action; it does not prove the message is fraudulent.</p>'}
 else if(v==='click'){box.className='challenge-result warning';box.innerHTML='<b>Risk branch: exposure may increase.</b><p>The next step could expose the user to a credential prompt. No link was opened in the real browser. The next safe stop is to close the page and avoid entering information.</p>'}
 else {box.className='challenge-result warning';box.innerHTML='<b>High-impact risk branch: code sharing.</b><p>A one-time code can authorize account access or an action. The simulation stops before any code is entered. End the call and contact the provider through an official channel.</p>'}
}
$('reconStart').addEventListener('click',start);
$('reconReset').addEventListener('click',function(){started=false;idx=0;choice=null;$('reconHeadline').textContent='One message is a clue. The sequence reveals the playbook.';$('reconIntro').textContent='Step through a simulated financial scam, inspect the evidence behind each inference, then replay it with a safer decision.';$('reconTimeline').innerHTML='<div class="empty-state">Press Reconstruct attack to begin the fictional case.</div>';$('reconProgress').textContent='0 / 5 EVENTS';$('reconRange').value=0;$('reconEventDetail').innerHTML='<div class="empty-state">Press Reconstruct attack to begin the fictional case.</div>';$('reconEvidence').innerHTML='<div class="empty-state">Evidence and limitations will appear here as you investigate.</div>';$('reconVerdictTitle').textContent='No conclusion yet';$('reconVerdictText').textContent='ScamChain should show its reasons and uncertainty—not just a score.';$('reconBreakpoints').innerHTML='<div class="empty-state">Run the reconstruction to compare possible warning points.</div>';document.querySelectorAll('[data-choice]').forEach(function(b){b.classList.remove('selected')});$('challengeResult').className='challenge-result';$('challengeResult').innerHTML='<b>Choose an action to run the experiment.</b><p>No real website, message, account or payment is contacted.</p>';toastRecon('Investigation reset.')});
function toastRecon(s){var t=$('toast');if(t){t.textContent=s;t.classList.remove('hidden');window.setTimeout(function(){t.classList.add('hidden')},2200)}}
$('reconRange').addEventListener('input',function(){if(!started)started=true;idx=Number(this.value);renderTimeline();renderDetail()});
$('reconTimeline').addEventListener('click',function(ev){var b=ev.target.closest('[data-recon-event]');if(!b)return;idx=Number(b.dataset.reconEvent);renderTimeline();renderDetail()});
document.querySelectorAll('[data-choice]').forEach(function(b){b.addEventListener('click',function(){choose(this.dataset.choice)})});
$('reconOfflineTest').addEventListener('click',function(){var ok=typeof window.fetch==='function'&&typeof document.createElement==='function';$('reconOfflineResult').textContent='Local interface check: passed. The challenge, timeline and evidence rendering run in this page. This check does not certify the entire application or guarantee every feature remains available without network access.'});
$('reconExport').addEventListener('click',function(){var payload={product:'ScamChain Attack Reconstruction Lab',team:'Beyond Binary',exported_at:new Date().toISOString(),demo_only:true,local_only:true,scenario:events.map(function(e){return {time:e.time,title:e.title,channel:e.channel,summary:e.summary,observed_or_simulated:e.kind,evidence:e.evidence,inference:e.inference,evidence_gap:e.gap}}),selected_event:started?events[idx].title:null,challenge_choice:choice,limitations:['All events are fictional training data.','No real website, inbox, file, account or payment was accessed.','Candidate stages are not proof of causation or attacker identity.','No live domain reputation or transaction verification is performed.']};var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='scamchain-attack-reconstruction.json';a.click();URL.revokeObjectURL(url)});
renderTimeline();
})();