"""Source-backed evidence hub for ScamChain.

Official Indian cyber-fraud figures are transcribed from PIB/MHA publications.
Public message samples are fetched from a research dataset at request time; if
the source is unavailable, the endpoint reports that honestly rather than
substituting fabricated examples.
"""
from fastapi import APIRouter
from fastapi.responses import HTMLResponse
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError
import csv, io, json

router = APIRouter()

STATS = [
    {"year": 2021, "complaints": 262846, "amount_crore": 551},
    {"year": 2022, "complaints": 694446, "amount_crore": 2290},
    {"year": 2023, "complaints": 1310357, "amount_crore": 7465},
    {"year": 2024, "complaints": 1918835, "amount_crore": 22848},
    {"year": 2025, "complaints": 2402579, "amount_crore": 22495},
]
SOURCES = [
    {"name":"Government of India — Ministry of Home Affairs / I4C (PIB)", "type":"Official reported financial-cyber-fraud statistics", "url":"https://www.pib.gov.in/PressReleasePage.aspx?PRID=2226441&lang=2&reg=3", "note":"NCRP complaints and amount reported for 2021–2025. These are reported complaints/losses, not a count of all scams or a detector benchmark."},
    {"name":"PhishTank (Cisco Talos)", "type":"Community-verified phishing URL intelligence", "url":"https://data.dev.phishtank.com/", "note":"Phishing URL feed/API; availability and verification status vary over time."},
    {"name":"Combined Labeled Smishing Dataset", "type":"Public labeled SMS research corpus", "url":"https://github.com/shaghayegh-hp/Smishing_Dataset", "note":"Repository describes messages labeled as smishing/non-smishing; labels are research annotations, not government-confirmed incidents."},
    {"name":"LegitPhish (Data in Brief, 2025)", "type":"Manually verified URL benchmark", "url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC12538017/", "note":"Published dataset reports 101,219 labeled URLs: 63,678 phishing and 37,540 legitimate."},
]

@router.get("/api/research-evidence")
def research_evidence():
    return {"official_statistics": STATS, "sources": SOURCES,
            "statistics_as_of": "2025 year-end figures, published by Government of India",
            "interpretation": "Official reported complaints and reported amounts are impact context, not classifier performance."}

@router.get("/api/public-message-samples")
def public_message_samples():
    url = "https://raw.githubusercontent.com/shaghayegh-hp/Smishing_Dataset/main/Combined-Labeled-Dataset.csv"
    try:
        req = Request(url, headers={"User-Agent":"ScamChain-research-prototype/1.0"})
        with urlopen(req, timeout=8) as response:
            raw = response.read(5_000_000).decode("utf-8", errors="replace")
        reader = csv.DictReader(io.StringIO(raw))
        fields = reader.fieldnames or []
        message_key = next((f for f in fields if f.lower().strip() in ("message","text","sms","sms_text")), None)
        smish_key = next((f for f in fields if "smishing" in f.lower()), None)
        spam_key = next((f for f in fields if "spam" in f.lower() or "label" in f.lower()), None)
        if not message_key:
            return {"status":"source_schema_changed","source_url":url,"count":0,"samples":[],"note":"Public source was reachable, but the message column could not be identified. No sample data was fabricated."}
        rows=[]
        seen=set()
        for row in reader:
            msg=(row.get(message_key) or "").strip()
            if len(msg)<12 or msg in seen: continue
            seen.add(msg)
            label=(row.get(smish_key) or row.get(spam_key) or "").strip()
            if label.lower() in ("1","smishing","phishing","spam","true","yes"):
                rows.append({"message":msg[:700],"label":"dataset-labelled smishing/spam","label_field":smish_key or spam_key})
            if len(rows)>=8: break
        return {"status":"live_source_loaded" if rows else "no_positive_rows_found","source_name":"Combined Labeled Smishing Dataset","source_url":"https://github.com/shaghayegh-hp/Smishing_Dataset","raw_data_url":url,"count":len(rows),"samples":rows,"note":"These are examples from a public research corpus. The dataset's labels are not independently re-verified by ScamChain."}
    except (URLError, HTTPError, TimeoutError, UnicodeError, csv.Error) as exc:
        return {"status":"source_unavailable","source_url":"https://github.com/shaghayegh-hp/Smishing_Dataset","count":0,"samples":[],"note":"Could not fetch the public dataset from the deployed server right now. No synthetic messages are shown as real evidence.","error":type(exc).__name__}


@router.get("/simulator", response_class=HTMLResponse)
def simulator_page():
    return HTMLResponse(r"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ScamChain | Live Simulator</title><style>
*{box-sizing:border-box}body{margin:0;background:#060b16;color:#e8f1ff;font:14px system-ui,sans-serif}header{padding:24px max(20px,calc((100vw - 1160px)/2));background:#0a1424;border-bottom:1px solid #263950}main{max-width:1160px;margin:auto;padding:24px 20px}.eyebrow{font-size:11px;letter-spacing:2px;color:#6de4f6}h1{font-size:32px;margin:8px 0}h2{font-size:18px}.muted{color:#9baec6;line-height:1.6}.layout{display:grid;grid-template-columns:1fr 1fr;gap:16px}.panel,.scenario{background:#0d192b;border:1px solid #263a53;border-radius:14px;padding:18px}.scenario{margin:12px 0}.scenario h3{margin:9px 0}.tag{font-size:10px;border:1px solid #66552b;color:#ffdc8c;border-radius:5px;padding:4px 7px}.tag.real{border-color:#27654f;color:#83efc2}.btn{border:1px solid #37869c;background:#173c51;color:#e7fbff;padding:10px 13px;border-radius:8px;cursor:pointer;font-weight:700}.btn.primary{background:#116b80}.btn:disabled{opacity:.45;cursor:wait}.notification{display:none;border:1px solid #efb74d;background:#211b11;border-radius:12px;padding:15px;margin:14px 0}.notification.show{display:block;animation:pop .25s ease-out}@keyframes pop{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}.msg{padding:13px;background:#070f1d;border:1px solid #2b405a;border-radius:9px;margin:10px 0;white-space:pre-wrap;line-height:1.6;overflow-wrap:anywhere}.result{display:none}.result.show{display:block}.risk{font-size:30px;font-weight:800;color:#ffcc70}.pill{display:inline-block;padding:4px 8px;border-radius:7px;background:#192b41;color:#bfeefa;font-size:11px;margin:3px}.event{padding:10px 0;border-bottom:1px solid #273950}.bar{height:8px;background:#1d2c41;border-radius:8px;overflow:hidden;margin:10px 0}.bar span{display:block;height:100%;background:linear-gradient(90deg,#56e0f6,#b58cff);width:0}.small{font-size:12px;color:#9baec6;line-height:1.6}a{color:#75e9ff}@media(max-width:760px){.layout{grid-template-columns:1fr}h1{font-size:26px}}
</style></head><body><header><div class="eyebrow">BEYOND BINARY / SCAMCHAIN</div><h1>Live Scam Simulator</h1><div class="muted">A judge-facing walkthrough: message arrives → in-app alert → judge checks it → ScamChain explains the evidence and reconstructs the risk chain.</div><p><a href="/">← Investigation Workbench</a> &nbsp;·&nbsp; <a href="/evidence">Real-World Evidence Lab ↗</a></p></header><main><div class="panel"><div class="eyebrow">HOW TO TRY IT</div><h2>Choose a scenario and trigger the incoming-message notification</h2><p class="muted">The included scenarios are clearly marked as illustrative demos. Use “Load public samples” to fetch research-dataset messages when the source is reachable. No real inbox, phone, or bank account is accessed.</p><button class="btn" id="loadReal">Load public labeled SMS samples</button><div id="realStatus" class="small" style="margin-top:8px">Public examples not loaded.</div></div><div class="layout" style="margin-top:16px"><section class="panel"><div class="eyebrow">01 / SCENARIO LIBRARY</div><div id="scenarios"></div></section><section class="panel"><div class="eyebrow">02 / IN-APP NOTIFICATION</div><div id="emptyNotice" class="muted">No message has arrived yet. Press “Simulate incoming message” on any scenario.</div><div id="notice" class="notification"><div class="eyebrow">NEW MESSAGE DETECTED · SIMULATION</div><h2 id="noticeTitle">Suspicious message</h2><div id="noticeSender" class="small"></div><div class="msg" id="noticeMessage"></div><button class="btn primary" id="check">Check this message →</button><div class="small" style="margin-top:8px">The alert is rendered inside this page; it is not a system-level notification.</div></div><div id="result" class="result"><div class="eyebrow">03 / SCAMCHAIN INVESTIGATION</div><h2 id="resultTitle">Analysis</h2><div class="risk" id="risk"></div><div class="bar"><span id="riskBar"></span></div><div id="badges"></div><h3>Why it was flagged</h3><div id="signals"></div><h3>Reconstructed chain</h3><div id="chain"></div><div id="limits" class="small" style="margin-top:12px"></div></div></section></div></main><script>
const demos=[
{id:"sms",title:"Bank account suspension SMS",kind:"ILLUSTRATIVE DEMO",sender:"Unknown SMS sender",message:"URGENT: Your bank account will be suspended today. Verify your account immediately and confirm your netbanking login details at the link below.",url:"https://banking-verify.example.invalid/login",beneficiary:"",new_device_login:false,beneficiary_created:false,transfer_initiated:false,desc:"Urgency + account threat + credential solicitation + suspicious-looking URL."},
{id:"upi",title:"UPI refund / collect-request lure",kind:"ILLUSTRATIVE DEMO",sender:"Unknown UPI contact",message:"Your refund is ready. To receive it, open the link and approve the UPI collect request. Share the OTP if support asks for verification.",url:"https://upi-refund-verify.example.invalid/claim",beneficiary:"",new_device_login:false,beneficiary_created:false,transfer_initiated:false,desc:"Refund lure + UPI approval pressure + OTP request."},
{id:"chain",title:"Multi-stage account takeover",kind:"ILLUSTRATIVE DEMO",sender:"Unknown sender",message:"Security alert: account access will be restricted. Verify your password and OTP immediately using the secure link.",url:"https://secure-account-check.example.invalid/verify",beneficiary:"New beneficiary (demo)",new_device_login:true,beneficiary_created:true,transfer_initiated:true,desc:"Message + credential/OTP request + unfamiliar login + new beneficiary + transfer signal."}
];
let selected=null;
const esc=s=>String(s||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function renderScenarios(items){document.getElementById("scenarios").innerHTML=items.map((x,i)=>'<div class="scenario"><span class="tag '+(x.kind==="PUBLIC RESEARCH DATASET"?"real":"")+'">'+esc(x.kind)+'</span><h3>'+esc(x.title)+'</h3><div class="small">'+esc(x.desc||"Public labeled message sample. Review original dataset before interpreting its label.")+'</div><div class="msg">'+esc(x.message)+'</div><button class="btn" data-id="'+esc(x.id)+'">Simulate incoming message</button></div>').join("");document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>arrive(items.find(x=>x.id===b.dataset.id)))}
function arrive(x){selected=x;document.getElementById("emptyNotice").style.display="none";document.getElementById("noticeTitle").textContent=x.title;document.getElementById("noticeSender").textContent="From: "+x.sender+" · "+x.kind;document.getElementById("noticeMessage").textContent=x.message;document.getElementById("notice").classList.add("show");document.getElementById("result").classList.remove("show");document.getElementById("notice").scrollIntoView({behavior:"smooth",block:"nearest"})}
document.getElementById("check").onclick=async()=>{if(!selected)return;const btn=document.getElementById("check");btn.disabled=true;btn.textContent="Analyzing evidence…";try{const r=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:selected.message,url:selected.url||"",sender:selected.sender||"",beneficiary:selected.beneficiary||"",new_device_login:!!selected.new_device_login,beneficiary_created:!!selected.beneficiary_created,transfer_initiated:!!selected.transfer_initiated})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Analysis failed");const score=Number(d.score?.risk_score??d.risk_score??d.risk??0);document.getElementById("resultTitle").textContent="Analysis complete · "+(d.case?.case_id||"case generated");document.getElementById("risk").textContent="Risk score: "+(Number.isFinite(score)?Math.round(score):"—")+"/100";document.getElementById("riskBar").style.width=Math.max(0,Math.min(100,Number.isFinite(score)?score:0))+"%";document.getElementById("badges").innerHTML='<span class="pill">Source: '+esc(selected.kind)+'</span><span class="pill">Rule / evidence analysis</span><span class="pill">Research prototype</span>';const signals=d.signals||d.signal_results||[];document.getElementById("signals").innerHTML=signals.length?signals.map(s=>'<div class="event"><b>'+esc(s.name||s.signal||s.type||"Signal")+'</b><div class="small">'+esc(s.explanation||s.reason||s.description||s.evidence||"Signal emitted by the analysis pipeline")+'</div></div>').join(""):'<div class="event small">No structured signal list was returned. Review the case output in the workbench.</div>';const replay=d.replay||d.case?.events||d.events||[];document.getElementById("chain").innerHTML=replay.length?replay.map((e,i)=>'<div class="event"><span class="pill">'+(i+1)+'</span><b>'+esc(e.event_type||e.type||e.stage||"Observed event")+'</b><div class="small">'+esc((e.evidence||e.description||[]).toString())+'</div></div>').join(""):'<div class="event small">No event replay returned for this sample.</div>';document.getElementById("limits").textContent="Interpretation: this is a prototype heuristic/model result, not a confirmed fraud verdict. The first two examples are illustrative and use reserved .invalid domains. Dataset examples retain their source label; the dataset label is not independently verified by ScamChain.";document.getElementById("result").classList.add("show");document.getElementById("result").scrollIntoView({behavior:"smooth",block:"nearest"})}catch(e){document.getElementById("resultTitle").textContent="Analysis could not complete";document.getElementById("limits").textContent=String(e.message||e);document.getElementById("result").classList.add("show")}finally{btn.disabled=false;btn.textContent="Check this message →"}};
document.getElementById("loadReal").onclick=async()=>{const el=document.getElementById("realStatus");el.textContent="Fetching public research dataset…";try{const d=await fetch("/api/public-message-samples").then(r=>r.json());el.textContent=d.note+" Status: "+d.status+".";if(d.samples&&d.samples.length){const real=d.samples.map((s,i)=>({id:"pub"+i,title:"Public SMS sample "+(i+1),kind:"PUBLIC RESEARCH DATASET",sender:"Dataset sample (sender not supplied)",message:s.message,url:"",desc:"Dataset label: "+s.label+". Source: Combined Labeled Smishing Dataset.",beneficiary:"",new_device_login:false,beneficiary_created:false,transfer_initiated:false}));renderScenarios([...demos,...real])}}catch(e){el.textContent="Public source could not be loaded. Existing illustrative scenarios remain available; no real examples were fabricated."}};
renderScenarios(demos);
</script></body></html>""")

@router.get("/evidence", response_class=HTMLResponse)
def evidence_page():
    return HTMLResponse(r"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ScamChain | Evidence Lab</title><style>
*{box-sizing:border-box}body{margin:0;background:#060b16;color:#e7effb;font:14px system-ui, sans-serif}header{padding:24px max(20px,calc((100vw - 1200px)/2));border-bottom:1px solid #25384f;background:#0a1221}a{color:#74e4f7}main{max-width:1200px;margin:auto;padding:26px 20px}.eyebrow{color:#6de2f4;font-size:11px;letter-spacing:2px}h1{margin:8px 0;font-size:32px}h2{font-size:19px}.sub{color:#9aacc3;line-height:1.6}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:20px 0}.card{background:#0d192b;border:1px solid #263a53;border-radius:13px;padding:17px;margin:12px 0}.num{font-size:27px;font-weight:750;color:#7ce8f5}.small{font-size:12px;color:#9aacc3;line-height:1.6}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;border-bottom:1px solid #263a53;padding:10px;font-size:12px}.msg{padding:13px;border:1px solid #31435b;background:#080f1c;border-radius:9px;margin:10px 0;white-space:pre-wrap;line-height:1.6}.tag{display:inline-block;color:#ffdc8c;border:1px solid #6a552b;padding:3px 7px;border-radius:6px;font-size:10px}.source{padding:12px 0;border-bottom:1px solid #24364c}.btn{background:#1b455a;color:#e8fbff;border:1px solid #398ba0;border-radius:8px;padding:10px 13px;cursor:pointer;font-weight:650}.warn{border-left:3px solid #ffc857;padding:10px 13px;background:#211b10;color:#f6dba0;font-size:12px;line-height:1.6}@media(max-width:700px){.metrics{grid-template-columns:1fr}.table{display:block;overflow:auto}}
</style></head><body><header><div class="eyebrow">BEYOND BINARY / SCAMCHAIN</div><h1>Real-World Evidence Lab</h1><div class="sub">Source-backed impact statistics, public message samples, and traceable research datasets.</div><p><a href="/">← Return to investigation workbench</a></p></header><main><div class="warn">Evidence integrity rule: official impact statistics are not detection accuracy. Public dataset labels are not automatically ground truth. If a live source fails, this page reports that failure instead of inventing samples.</div><section class="card"><div class="eyebrow">01 / NATIONAL IMPACT</div><h2>Reported financial cyber-fraud complaints in India</h2><p class="sub">Government of India NCRP/I4C figures, 2021–2025. Amounts are reported losses in ₹ crore.</p><div class="metrics" id="metrics"></div><div id="stats"></div><p class="small">Source: <a href="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2226441&lang=2&reg=3" target="_blank" rel="noreferrer">Press Information Bureau / Ministry of Home Affairs</a>. Reported complaint counts can reflect changes in reporting and should not be interpreted as the total number of all scams.</p></section><section class="card"><div class="eyebrow">02 / REAL MESSAGE CORPUS</div><h2>Publicly labeled smishing examples</h2><p class="sub">Fetched on demand from a public research dataset. Messages appear only if the source returns rows; we do not substitute generated examples.</p><button class="btn" id="load">Fetch public samples</button><div id="samples" class="small" style="margin-top:14px">Not loaded yet. Click the button to request the source dataset.</div></section><section class="card"><div class="eyebrow">03 / TRACEABLE SOURCES</div><h2>Research and threat-intelligence sources</h2><div id="sources"></div></section><section class="card"><div class="eyebrow">04 / VALIDATION STANDARD</div><h2>What we will measure against labeled data</h2><div class="metrics"><div><div class="num">Precision</div><div class="small">Of messages flagged, how many are labeled scams?</div></div><div><div class="num">Recall</div><div class="small">Of labeled scam messages, how many did the detector catch?</div></div><div><div class="num">False-positive rate</div><div class="small">How often legitimate messages are incorrectly flagged.</div></div></div><p class="small">The app currently does not claim these are measured metrics for real-world data. They must be computed from a held-out labeled test set, with duplicates removed and source/date documented.</p></section></main><script>
const fmt=n=>new Intl.NumberFormat('en-IN').format(n);
async function init(){try{const d=await fetch('/api/research-evidence').then(r=>r.json());const s=d.official_statistics;const latest=s[s.length-1];document.getElementById('metrics').innerHTML='<div><div class="num">'+fmt(latest.complaints)+'</div><div class="small">Financial-fraud complaints in 2025</div></div><div><div class="num">₹'+fmt(latest.amount_crore)+' crore</div><div class="small">Amount reported in 2025</div></div><div><div class="num">₹8,189+ crore</div><div class="small">Reported amount saved through CFCFRMS by 31 Dec 2025</div></div>';document.getElementById('stats').innerHTML='<table class="table"><thead><tr><th>Year</th><th>Complaints</th><th>Amount reported</th></tr></thead><tbody>'+s.map(x=>'<tr><td>'+x.year+'</td><td>'+fmt(x.complaints)+'</td><td>₹'+fmt(x.amount_crore)+' crore</td></tr>').join('')+'</tbody></table>';document.getElementById('sources').innerHTML=d.sources.map(x=>'<div class="source"><b>'+x.name+'</b><div class="small">'+x.type+'</div><div class="small">'+x.note+'</div><a href="'+x.url+'" target="_blank" rel="noreferrer">Open source ↗</a></div>').join('')}catch(e){document.getElementById('stats').textContent='Could not load official evidence metadata.'}}
document.getElementById('load').onclick=async()=>{const box=document.getElementById('samples');box.textContent='Fetching the public research corpus…';try{const d=await fetch('/api/public-message-samples').then(r=>r.json());box.innerHTML='<p><b>Status:</b> '+d.status+' · <b>Rows returned:</b> '+d.count+'</p><p>'+d.note+'</p>'+(d.samples||[]).map((x,i)=>'<div class="msg"><span class="tag">DATASET LABEL: '+x.label+'</span><p><b>Sample '+(i+1)+'</b></p>'+String(x.message).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))+'</div>').join('')+'<p><a href="'+d.source_url+'" target="_blank" rel="noreferrer">Inspect original dataset ↗</a></p>'}catch(e){box.textContent='Source request failed. No message examples were fabricated.'}};
init();
</script></body></html>""")
